// <auto-generated />
using DemoApplication.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201005044141_BranchMigration")]
    partial class BranchMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClassLibrary.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bank");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Bank1",
                            Name = "Bank 1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Bank2",
                            Name = "Bank 2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Bank3",
                            Name = "Bank 3"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Bank4",
                            Name = "Bank 4"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bank")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("District")
                        .HasColumnType("int");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Branchs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bank = 1,
                            BranchName = "Default Branch",
                            District = 1,
                            IFSCCode = "BR001",
                            State = 1
                        });
                });

            modelBuilder.Entity("ClassLibrary.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Amritsar",
                            Name = "Amritsar",
                            StateID = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Pathankot",
                            Name = "Pathankot",
                            StateID = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "Indore",
                            Name = "Indore",
                            StateID = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "Bhopal",
                            Name = "Bhopal",
                            StateID = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "Pune",
                            Name = "Pune",
                            StateID = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "Mumbai",
                            Name = "Mumbai",
                            StateID = 3
                        });
                });

            modelBuilder.Entity("ClassLibrary.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Punjab",
                            Name = "Punjab"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MadhyaPradesh",
                            Name = "MadhyaPradesh"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Maharashtra",
                            Name = "Maharashtra"
                        });
                });

            modelBuilder.Entity("ClassLibrary.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
